"""
Node 2: Discovery Node
Performs web searches using Exa (neural/semantic search) and finds potential brand URLs.
"""
from typing import List, Dict, Any, Union
import os
from models import ProspectorState, QuerySearchResults
from .utils import normalize_url
from exa_py import Exa

async def discovery_node(state: Union[ProspectorState, Dict[str, Any]]) -> Dict[str, Any]:
    """
    Discovery - Find potential brand URLs using REAL web search with Exa (neural/semantic).
    Saves results to the state (replacing legacy global mutable list).
    """
    # Handle state
    search_queries = state.search_queries if hasattr(state, "search_queries") else state.get("search_queries", [])
    query_origins = state.query_origins if hasattr(state, "query_origins") else state.get("query_origins", [])
    
    print(f"[DISCOVERY] Starting Exa search with {len(search_queries)} queries...")
    
    candidate_urls: List[str] = []
    unique_urls: set = set()
    search_results: List[QuerySearchResults] = []
    new_progress = []
    
    try:
        total_queries = len(search_queries)
        new_progress.append(f"🔍 Iniciando busca com {total_queries} queries...")
        
        exa = Exa(api_key=os.environ.get("EXA_API_KEY"))
        exclude_domains = [
            # E-commerce giants
            "amazon.com", "ebay.com", "walmart.com", "target.com",
            "nordstrom.com", "saksfifthavenue.com", "neimanmarcus.com",
            "aliexpress.com", "alibaba.com",
            # Review / listing / directory sites (never actual brands)
            "yelp.com", "yellowpages.com", "tripadvisor.com",
            "trustpilot.com", "glassdoor.com", "indeed.com",
            "foursquare.com", "kompass.com",
            # Social media (brand pages, not brand websites)
            "facebook.com", "instagram.com", "tiktok.com",
            "twitter.com", "x.com", "linkedin.com",
            "pinterest.com", "reddit.com", "quora.com",
            # Maps / navigation
            "google.com", "maps.google.com",
            # Reference / wiki
            "wikipedia.org", "wikidata.org",
            # Listicle / editorial farms (return articles, not brand sites)
            "timeout.com", "esquire.com", "gq.com",
        ]
        
        # Process all queries generated by the initializer
        for i, query in enumerate(search_queries):
            origin = query_origins[i] if i < len(query_origins) else "Unknown"
            try:
                print(f"[EXA] Query {i + 1} ({origin}): \"{query}\"")
                new_progress.append(f"🔎 Query {i + 1}: \"{query}\"")
                
                response = exa.search(
                    query,
                    num_results=20,
                    type="auto",
                    exclude_domains=exclude_domains,
                    contents={"text": {"maxCharacters": 10000}, "highlights": True}
                )
                
                query_results = QuerySearchResults(
                    query_index=i, 
                    query=query, 
                    query_origin=origin,
                    results=[]
                )
                for result in response.results:
                    url = result.url or ""
                    if url and normalize_url(url) not in unique_urls:
                        unique_urls.add(normalize_url(url))
                        candidate_urls.append(url)
                        
                        highlights_str = " ".join(result.highlights) if hasattr(result, "highlights") and result.highlights else ""
                        text_content = result.text if hasattr(result, "text") and result.text else ""
                        
                        query_results.results.append({
                            "url": url,
                            "title": result.title or "",
                            "content": highlights_str,
                            "text": text_content,  # Full page text from Exa index
                            "query_origin": origin
                        })
                search_results.append(query_results)
                new_progress.append(f"   ✓ {len(response.results)} resultados")
            except Exception as e:
                print(f"[EXA] Error: {e}")
                new_progress.append(f"   ⚠️ Query {i + 1} falhou")
        
        new_progress.append(f"📈 Encontradas {len(candidate_urls)} URLs únicos")

        print(f"[DISCOVERY] Found {len(candidate_urls)} unique candidate URLs")
        for i, url in enumerate(candidate_urls[:10]):
            print(f"   URL {i+1}: {url}")
        
        return {
            "candidate_urls": candidate_urls,
            "search_results": search_results, # Save to state for validation_node
            "progress": new_progress,
        }
    except Exception as error:
        return {
            "error": str(error),
            "progress": new_progress + ["❌ Descoberta falhou"],
        }
